version: "3.5"
services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command:
      [
        "./wait-for-it.sh",
        "${DB_HOST}:${DB_PORT}",
        "-t",
        "120",
        "--",
        "./start-channels-worker.sh"
      ]
  redis:
    image: redis:latest

  db:
    image: postgres:10.1-alpine

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - worker
    command:
      [
        "./wait-for-it.sh",
        "${DB_HOST}:${DB_PORT}",
        "-t",
        "120",
        "--",
        "./start-development-server.sh",
      ]
